default: true

# MD013 line-length - Line length
# https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013
MD013:
    line_length: 80
    heading_line_length: 80
    code_block_line_length: 80
    code_blocks: false
    tables: true
    headings: true
    headers: true
    strict: false

# MD026 no-trailing-punctuation - Trailing punctuation in heading
# https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md026
MD026:
    punctuation: .,;:。，；：

# MD033 no-inline-html - Inline HTML
# https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md033
MD033:
    allowed_elements: [
        "center",
        "font",
        "img",
        "br"
    ]
